### PR TITLE
fix(semantic-dom-diff): allow assertion message

### LINKED ISSUE #1477: [semantic-dom-diff] Allow specifying assertion message
I'm used to being able to set the assertion message as the last argument to the assertion function:
```ts
assert.equal(a, b, 'a and b are not the same');
```
`assert.lightDom.equal` doesn't appear to accept a message argument.

### PR DESCRIPTION
**Pull request by bennypowers**
also fixes types

fixes #1477

### CODE REVIEW

File: packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts [hunk 1]
```diff
@@ -1,19 +1,37 @@
...
+      dom: Assertion;
+      lightDom: Assertion;
+      shadowDom: Assertion;
+      notEqual(actual: Object, expected: Object, message?: string): void;
+      equalSnapshot(options?: Object): Assertion;
+      notEqualSnapshot(options?: Object): Assertion;
+    }
+
+    interface Assert {
+      dom: Pick<Assertion, 'equal'|'notEqual'|'equalSnapshot'|'notEqualSnapshot'>;
```
Comment (bennypowers) [inline packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts:17]: I think a "truer" approach would be to implement the entire interface in JavaScript, just throw errors on nonsense assertions. 

cc: @LarsDenBakker

File: packages/semantic-dom-diff/chai-dom-diff.d.ts [hunk 2]
```diff
@@ -1,7 +1,24 @@
...
+/// <reference path="./chai-dom-diff-plugin.d.ts" />
 
 /**
- * @param {any} chai
- * @param {any} utils
+ * @param chai
+ * @param utils
  */
-export const chaiDomDiff: (chai: any, utils: any) => void;
+export const chaiDomDiff: (chai: typeof Chai, utils: any) => void;
```
Comment (bennypowers) [inline packages/semantic-dom-diff/chai-dom-diff.d.ts:7]: should maybe be a type assertion of ChaiPlugin

File: packages/semantic-dom-diff/chai-dom-diff.d.ts [hunk 3]
```diff
@@ -1,7 +1,24 @@
...
+
+// No idea what this is
+type Snapshot = any;
```
Comment (bennypowers) [inline packages/semantic-dom-diff/chai-dom-diff.d.ts:10]: seriously, what is this?

File: packages/semantic-dom-diff/chai-dom-diff.js [hunk 4]
```diff
@@ -37,21 +57,31 @@ export const chaiDomDiff = (chai, utils) => {
...
     } else {
-      assertion.equal(expectedDiffableHTML);
+      assertion.equal(expectedDiffableHTML, message);
     }
   };
 
   /** DOM assertion for `should` and `expect` interfaces. */
   const domEquals = _super =>
+    /**
+     * @this {any}
```
Comment (bennypowers) [inline packages/semantic-dom-diff/chai-dom-diff.js:83]: what is `this` here?

File: packages/semantic-dom-diff/chai-dom-diff.js [hunk 5]
```diff
@@ -80,8 +110,15 @@ export const chaiDomDiff = (chai, utils) => {
   const context = window.__mocha_context__;
   const snapshotState = window.__snapshot__;
 
-  /** Base HTML snapshot assertion for `assert` interface. */
-  function assertHtmlEqualsSnapshot(actual, options, negate = false) {
+  /**
+   * Base HTML snapshot assertion for `assert` interface.
+   * @this {any}
```
Comment (bennypowers) [inline packages/semantic-dom-diff/chai-dom-diff.js:115]: What is `this` here?

File: packages/semantic-dom-diff/chai-dom-diff.js [hunk 6]
```diff
@@ -119,7 +156,10 @@ export const chaiDomDiff = (chai, utils) => {
     }
   }
 
-  /** Snapshot assertion for `should` and `expect` interfaces. */
+  /**
+   * Snapshot assertion for `should` and `expect` interfaces.
+   * @this {any}
```
Comment (bennypowers) [inline packages/semantic-dom-diff/chai-dom-diff.js:161]: what is `this` here?

**Comment by bennypowers** [comment]
Notes to reviewers: I'm pretty sure I didn't break any public apis here, hence the patch version, but please double-check

File: packages/semantic-dom-diff/chai-dom-diff.js (hunk 4 above)
Comment (daKmoR) [reply packages/semantic-dom-diff/chai-dom-diff.js:83]: chai itself... chai works by binding its plugin function to itself... that's also the reasons that `handleDom` can not be an arrow function... as it would break chains plugin "system"...

it's a very old school system... because it's old like really old 😅

Comment (bennypowers) [reply packages/semantic-dom-diff/chai-dom-diff.js:83]: is that Chai or Chai.ChaiStatic?

Comment (bennypowers) [reply packages/semantic-dom-diff/chai-dom-diff.js:83]: I think this instance is actually `Chai.AssertionStatic`

File: packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts (hunk 1 above)
Comment (LarsDenBakker) [reply packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts:17]: I didn't write this code, so I'm not sure :p

File: packages/semantic-dom-diff/chai-dom-diff.d.ts (hunk 3 above)
Comment (LarsDenBakker) [reply packages/semantic-dom-diff/chai-dom-diff.d.ts:6]: this comes from https://www.npmjs.com/package/mocha-snapshots and https://www.npmjs.com/package/karma-mocha-snapshot

File: packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts (hunk 1 above)
Comment (bennypowers) [reply packages/semantic-dom-diff/chai-dom-diff-plugin.d.ts:17]: YOLO
