### PR TITLE
fix(eslint-plugin-lit-a11y): qualified specifiers

### LINKED ISSUE #1911: [eslint-plugin-lit-a11y]: refactor to compose rules, test settings
## Composing Rules

Currently, we copy logic into each rule to verify that the file imports lit-html's `html`, This is great for users but hard to maintain, as we have to remember to copy in the logic for each rule.

We can compose rules with https://github.com/not-an-aardvark/eslint-rule-composer

so, instead of adding a predicate in each rule's AST visitor, we can just compose them together:

```js
const { filterReports } = require('eslint-rule-composer');
const eslint = require('eslint');
const hasLitHtmlImport = require('../utils/hasLitHtmlImport');

const TheRule = { /*...*/ }

module.exports = filterReports(TheRule, hasLitHtmlImport);
```

Much DRYer.

-----

## Applying `settings` in tests

In tests, we map over each test case to add an import statement for lit-html's `html`. We can apply settings for a test run with:

```js
const ruleTester = new RuleTester({ settings: { myPluginSpecificSetting: ['lol'] } });
```

we could make `litHtmlSources` opt out by accepting `false` as an option, then disable checking for tests with

```js
const ruleTester = new RuleTester({ settings: { litHtmlSources: false } });
```

### LINKED ISSUE #1916: [eslint-plugin-lit-a11y] improve valid lithtml sources check
Currently we do a check to see if the `node.source.value` is included in the `validLitHtmlSources` array. 

https://github.com/open-wc/open-wc/blob/73c500197e1403ac7c4ec78412f922e52a58c696/packages/eslint-plugin-lit-a11y/lib/utils/utils.js#L24

What currently works:
```json
      "litHtmlSources": ["ing-web/core.js"]
```

```js
import {html} from 'ing-web/core.js';
```

But if you only specify `ing-web` in `litHtmlSources`, it wont work. This can be pretty confusing. We should simplify this check and allow bare import specifiers like `ing-web`.

### PR DESCRIPTION
**Pull request by bennypowers**
also refactors rules to extend from common base
common base checks whether lit-html is imported
import check now supports namespaces and aliases

fixes #1911
fixes #1916

NOTE TO REVIEWERS: please carefully check test cases

### CODE REVIEW

File: packages/eslint-plugin-lit-a11y/lib/rules/accessible-emoji.js [hunk 1]
```diff
@@ -92,4 +85,4 @@ const AccessibleEmojiRule = {
   },
 };
 
-module.exports = AccessibleEmojiRule;
+module.exports = ruleExtender(AccessibleEmojiRule, HasLitHtmlImportRuleExtension);
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/lib/rules/accessible-emoji.js:88]: > ok my solution relies on the ImportDeclaration visitor in createAdditionalVisitors running before the subclass rule, I hope that's a good assumption

Does ruleExtender just merge just two objects together? Or does the order matter?

File: packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js [hunk 2]
```diff
@@ -0,0 +1,161 @@
...
+    .filter(Boolean);
+}
+
+const HasLitHtmlImportRuleExtension = {
+  /**
+   * @param {LitA11yRuleContext} context
+   * @return {import('eslint').Rule.RuleListener}
+   */
+  createAdditionalVisitors(context) {
+    /** if user set `litHtmlSources` to literal `false`, analyse all html-tagged literals */
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js:118]: What is the usecase for setting `litHtmlSources` to `false`?

File: packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js [hunk 3]
```diff
@@ -0,0 +1,161 @@
...
+    /* eslint-enable no-param-reassign */
+  },
+
+  /**
+   * @param {import('eslint').Rule.RuleMetaData} meta
+   * @param {LitA11yRuleContext} context
+   */
+  reportOverrides(meta, context) {
+    const { shouldAnalyseHtmlTaggedLiterals } = context.parserServices || {};
+    return !!shouldAnalyseHtmlTaggedLiterals;
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js:155]: What does this method do?

File: packages/eslint-plugin-lit-a11y/lib/utils/isLitHtmlTemplate.js [hunk 4]
```diff
@@ -4,37 +4,57 @@
...
 /**
- * Whether a node is a lit-html html-tagged template expression
+ * Whether a node is a lit-element css-tagged template expression
  * @param {import('eslint').Rule.Node} node
- * @returns {node is LitTaggedExpression<'html'>}
+ * @param {import('./HasLitHtmlImportRuleExtension').LitA11yRuleContext} context
+ * @returns {node is LitTaggedExpression<'css'>}
  */
-function isHtmlTaggedTemplate(node) {
+// future iterations might want to apply svg a11y checks,
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/lib/utils/isLitHtmlTemplate.js:37]: this comment is duplicate here, i think this one should be removed, and the one lower down should be kept

File: packages/eslint-plugin-lit-a11y/package.json [hunk 5]
```diff
@@ -31,6 +31,7 @@
     "dom5": "^3.0.1",
     "emoji-regex": "^9.0.0",
     "eslint": "^7.6.0",
+    "eslint-rule-extender": "^0.0.1",
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/package.json:34]: should we pin the version in case they do a breaking change since its <1?

File: packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js [hunk 6]
```diff
@@ -10,18 +10,19 @@
...
 const { RuleTester } = require('eslint');
 const rule = require('../../../lib/rules/autocomplete-valid');
-const { prependLitHtmlImport } = require('../../../lib/utils/utils.js');
 
 //------------------------------------------------------------------------------
 // Tests
 //------------------------------------------------------------------------------
 
 const ruleTester = new RuleTester({
+  settings: { litHtmlSources: false },
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js:19]: why do we have false as the default setting everywhere in the tests?

File: packages/eslint-plugin-lit-a11y/lib/rules/accessible-emoji.js (hunk 1 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/lib/rules/accessible-emoji.js:88]: The second arg is its own type, with it's own special methods

File: packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js (hunk 2 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js:118]: Disable checking. I forgot to document that in readme

File: packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js (hunk 3 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js:155]: https://www.npmjs.com/package/eslint-rule-extender

What were doing here iis skipping reporting

File: packages/eslint-plugin-lit-a11y/package.json (hunk 5 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/package.json:34]: Sure

File: packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js (hunk 6 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js:19]: To disable checking, so as not to pollute tests

File: packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js (hunk 3 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js:167]: this function can return 
- `true`: report original message
- `false`: skip reporting
- `RuleMetadata`: replace message

File: packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js (hunk 6 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/tests/lib/rules/autocomplete-valid.js:19]: in other words, this takes the place of `valid: [...].map(prependLitHtmlImport)`

**Comment by bennypowers** [comment]
tests are failing on es-dev-server?

**Comment by thepassle** [comment]
> tests are failing on es-dev-server?

Probably just flakiness. I retried the pipeline

File: packages/eslint-plugin-lit-a11y/README.md [hunk 7]
```diff
@@ -64,6 +64,16 @@ In this case, you can configure `@apollo-elements/lit-apollo` as a valid lit-htm
 
 The reason for this check is that project may make use of multiple rendering libraries, which may have similar apis, like for example [`htm`](https://github.com/developit/htm), which also uses a `html` tagged template literal, but handles syntax differently.
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/README.md:65]: I made a typo just above here ^

> By default, only templates imported from 'lit-html' or 'lit-element' are exported.

That should be:

> By default, only templates imported from 'lit-html' or 'lit-element' are linted.

Could we take that along in this PR? 😬 sorry :p

File: packages/eslint-plugin-lit-a11y/lib/rules/tabindex-no-positive.js [hunk 8]
```diff
@@ -24,43 +24,44 @@ const TabindexNoPositiveRule = {
...
+                if (isExpressionPlaceholder(literal)) {
+                  const expr = analyzer.getExpressionFromPlaceholder(literal);
+
+                  // if the interpolated value a simple literal expression, we can analyze it
+                  if (isLiteral(expr)) literal = `${expr.value}`;
+                  // if the interpolated value is a variable name or some other
+                  // non-literal expression, we can't analyze it
+                  else return;
+
+                  if (!literal) return;
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/lib/rules/tabindex-no-positive.js:54]: Isnt this check redundant?

File: packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js (hunk 3 above)
Comment (thepassle) [reply packages/eslint-plugin-lit-a11y/lib/utils/HasLitHtmlImportRuleExtension.js:167]: gotcha 👍

File: packages/eslint-plugin-lit-a11y/lib/utils/isLitHtmlTemplate.js [hunk 9]
```diff
@@ -4,37 +4,56 @@
...
 
 /**
  * Whether a node is a lit-html svg-tagged template expression
  * @param {import('eslint').Rule.Node} node
+ * @param {import('./HasLitHtmlImportRuleExtension').LitA11yRuleContext} context
  * @returns {node is LitTaggedExpression<'svg'>}
  */
-function isSvgTaggedTemplate(node) {
+// eslint-disable-next-line no-unused-vars
+function isSvgTaggedTemplate(node, context) {
```
Comment (thepassle) [inline packages/eslint-plugin-lit-a11y/lib/utils/isLitHtmlTemplate.js:56]: note for the future: we could add a rule to enforce accessible inline svgs https://css-tricks.com/accessible-svgs/

File: packages/eslint-plugin-lit-a11y/README.md (hunk 7 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/README.md:65]: done

File: packages/eslint-plugin-lit-a11y/lib/rules/tabindex-no-positive.js (hunk 8 above)
Comment (bennypowers) [reply packages/eslint-plugin-lit-a11y/lib/rules/tabindex-no-positive.js:54]: apparently, committing...

**Comment by thepassle** [comment]
image

troll

**Comment by thepassle** [comment]
Okay, done with my review, left a few minor comments. I think we should just move forward with this PR and merge it if pipeline passes, but itd be nice to do some real life testing, especially with regard to the imports

**Comment by bennypowers** [comment]
this may conflict with #1918. @koenvg i'll be available to help you resolve if you like

**Review by thepassle — APPROVED** [review]

**Comment by thepassle** [comment]
we _gotta_ split PRs like this up in the future 😂
