### PR TITLE
fix(testing-karma): export types

### LINKED ISSUE #1475: [testing-karma] No typings available
`@open-wc/testing-karma` appears to have no typings.

### PR DESCRIPTION
**Pull request by bennypowers**
fixes #1475

### CODE REVIEW

**Comment by bennypowers** [comment]
@lars note the error on `packages/testing-karma/src/create-default-config.js`

I'm not sure if the bug is on the ts side or on the js side.

File: packages/karma-esm/src/esm-config.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ const deepmerge = require('deepmerge');
  * @property {string[]} [babelModernExclude]
  * @property {string[]} [babelModuleExclude]
  * @property {boolean} [preserveSymlinks]
- * @property {import('./utils/inject-polyfills-loader-types').PolyfillsLoaderConfig} [polyfillsLoader]
+ * @property {Partial<import('polyfills-loader').PolyfillsLoaderConfig>} [polyfillsLoader]
```
Comment (daKmoR) [inline packages/karma-esm/src/esm-config.js:20]: this dependency is missing in `package.json`?
